#!/bin/sh

per=$(acpi -b | grep -o '[0-9]*%' | tr -d %)

icon() {
	[ "$(acpi -b | grep -q Charging)" ] && echo "" && exit

	if [ "$per" -gt "90" ]; then
		icon="󰁹"
	elif [ "$per" -gt "80" ]; then
		icon="󰂂"
	elif [ "$per" -gt "70" ]; then
		icon="󰂀"
	elif [ "$per" -gt "60" ]; then
		icon="󰁿"
	elif [ "$per" -gt "50" ]; then
		icon="󰁾"
	elif [ "$per" -gt "40" ]; then
		icon="󰁾"
	elif [ "$per" -gt "30" ]; then
		icon="󰁽"
	elif [ "$per" -gt "20" ]; then
		icon="󰁼"
	elif [ "$per" -gt "10" ]; then
		icon="󰁻"
		dunstify -u critical "Battery Low" "Connect Charger"
	elif [ "$per" -gt "0" ]; then
		icon="󰂎"
		dunstify -u critical "Battery Low" "Connect Charger"
	else
			echo  && exit
	fi
	echo "$icon"
}

percent() {
	echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit